### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by ok-soosoo** [ok-soosoo/fe-github-practice#1]
### 만들고자 하는 기능
1. [x] 할일 작성
2. [x] 작성한 내용 업데이트
3. [x] 작성한 내용 삭제
4. [x] 작성한 내용 리스트업

### 예상 작업 시간
1D
